// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Business struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	CreatedAt      time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt      *time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt      *time.Time `db:"deleted_at" json:"deleted_at"`
	BusinessName   string     `db:"business_name" json:"business_name"`
	BusinessAvatar *string    `db:"business_avatar" json:"business_avatar"`
	OwnerID        uuid.UUID  `db:"owner_id" json:"owner_id"`
}

type User struct {
	ID            uuid.UUID  `db:"id" json:"id"`
	CreatedAt     time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt     *time.Time `db:"updated_at" json:"updated_at"`
	DeletedAt     *time.Time `db:"deleted_at" json:"deleted_at"`
	Fullname      string     `db:"fullname" json:"fullname"`
	Email         string     `db:"email" json:"email"`
	Phone         string     `db:"phone" json:"phone"`
	Password      string     `db:"password" json:"password"`
	EmailVerified bool       `db:"email_verified" json:"email_verified"`
}

type UserEmailVerification struct {
	Email     string    `db:"email" json:"email"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	Code      string    `db:"code" json:"code"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
}
