// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: user.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const findUserById = `-- name: FindUserById :one
Select id, created_at, updated_at, deleted_at, fullname, email, password, email_verified from users where id=$1 LIMIT 1
`

func (q *Queries) FindUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Fullname,
		&i.Email,
		&i.Password,
		&i.EmailVerified,
	)
	return i, err
}
