-- +goose Up

ALTER TABLE client
ALTER COLUMN fullname DROP NOT NULL,
ALTER COLUMN email DROP NOT NULL,
ALTER COLUMN phone DROP NOT NULL;

-- +goose Down
ALTER TABLE client
ALTER COLUMN fullname SET NOT NULL,
ALTER COLUMN email SET NOT NULL,
ALTER COLUMN phone SET NOT NULL;