basePath: /
definitions:
  database.Business:
    properties:
      business_avatar:
        type: string
      business_name:
        type: string
      count_id:
        type: integer
      created_at:
        $ref: '#/definitions/pgtype.Timestamptz'
      deleted_at:
        $ref: '#/definitions/pgtype.Timestamptz'
      id:
        type: string
      invoice_count:
        type: number
      owner_id:
        type: string
      updated_at:
        $ref: '#/definitions/pgtype.Timestamptz'
    type: object
  database.User:
    properties:
      count_id:
        type: integer
      created_at:
        $ref: '#/definitions/pgtype.Timestamptz'
      deleted_at:
        $ref: '#/definitions/pgtype.Timestamptz'
      email:
        type: string
      email_verified:
        type: boolean
      fullname:
        type: string
      id:
        type: string
      password:
        type: string
      updated_at:
        $ref: '#/definitions/pgtype.Timestamptz'
    type: object
  handlers.CreateUserInput:
    properties:
      email:
        type: string
      fullname:
        type: string
      password:
        type: string
    required:
    - email
    - fullname
    - password
    type: object
  handlers.ResendEmailOtpInput:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  handlers.userBusinessHolder:
    properties:
      business:
        $ref: '#/definitions/database.Business'
      user:
        $ref: '#/definitions/database.User'
    type: object
  pgtype.InfinityModifier:
    enum:
    - 1
    - 0
    - -1
    type: integer
    x-enum-varnames:
    - Infinity
    - Finite
    - NegativeInfinity
  pgtype.Timestamptz:
    properties:
      infinityModifier:
        $ref: '#/definitions/pgtype.InfinityModifier'
      time:
        type: string
      valid:
        type: boolean
    type: object
  util.ErrorResponse:
    properties:
      errors:
        items:
          type: string
        type: array
      message:
        type: string
    type: object
  util.SuccessResponse:
    properties:
      message:
        type: string
    type: object
  util.SuccessResponseWithData-database_User:
    properties:
      data:
        $ref: '#/definitions/database.User'
      message:
        type: string
    type: object
  util.SuccessResponseWithData-handlers_userBusinessHolder:
    properties:
      data:
        $ref: '#/definitions/handlers.userBusinessHolder'
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: Blanq Invoice API
  version: "1.0"
paths:
  /auth/resendEmailOtp:
    post:
      consumes:
      - application/json
      description: Resend EmailOTP
      parameters:
      - description: ' '
        in: body
        name: ResendEmailOtpInput
        required: true
        schema:
          $ref: '#/definitions/handlers.ResendEmailOtpInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.SuccessResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Resend EmailOTP
      tags:
      - Authentication
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: With the Bearer prefix
        in: header
        name: Authorization
        required: true
        type: string
      - description: ' '
        in: body
        name: CreateUserInput
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateUserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.SuccessResponseWithData-database_User'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Signup
      tags:
      - Authentication
  /me:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.SuccessResponseWithData-handlers_userBusinessHolder'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Get User Account Details
      tags:
      - Account Details
swagger: "2.0"
